import Link from "next/link";
import { getActiveBanners, getActiveOffers, getCategories, getProducts } from "@/lib/store";

function Price({ amount }: { amount: number }) { return <>{amount.toLocaleString("ar-PS")} ₪</>; }

export default async function Home() {
  const [banners, categories, offers, products] = await Promise.all([getActiveBanners(), getCategories(), getActiveOffers(), getProducts()]);
  const hero = banners[0];
  const heroHref=hero?.destination_type==="offer"&&hero.destination_id?`/shop?offer=${hero.destination_id}`:hero?.destination_type==="category"&&hero.destination_id?`/shop?category=${hero.destination_id}`:hero?.destination_url?.startsWith("/")?hero.destination_url:"/shop";
  return <main dir="rtl" className="min-h-screen bg-[#fffdfc] text-[#201d1c]">
    <div className="bg-[#201d1c] px-4 py-2.5 text-center text-[10px] text-white">توصيل إلى جميع مناطق فلسطين</div>
    <header className="sticky top-0 z-40 border-b border-black/[.06] bg-[#fffdfc]/95 backdrop-blur-md"><div className="mx-auto flex h-[82px] max-w-[1440px] items-center justify-between px-5 lg:px-10">
      <nav className="hidden flex-1 items-center gap-7 text-xs lg:flex"><Link href="/">الرئيسية</Link><Link href="/shop">المتجر</Link><Link href="/shop?offers=true">العروض</Link></nav>
      <Link href="/" className="flex flex-1 flex-col items-center text-[#171514]"><span className="font-serif text-[27px] leading-none">Glitter</span><span className="mt-1 text-[7px] tracking-[.38em]">ACCESSORIES</span></Link>
      <nav className="flex flex-1 items-center justify-end gap-5 text-xs"><Link href="/search" aria-label="البحث">⌕</Link><Link href="/account">حسابي</Link><Link href="/favorites">♡</Link><Link href="/cart">السلة</Link></nav>
    </div></header>
    {hero ? <section className="relative flex min-h-[560px] items-center overflow-hidden bg-[#6b5149] md:min-h-[690px]">{hero.image && (hero.media_type==="video"?<video src={hero.image} autoPlay muted loop playsInline aria-label={hero.title} className="absolute inset-0 h-full w-full object-cover"/>:<img src={hero.image} alt={hero.title} className="absolute inset-0 h-full w-full object-cover"/>)}<div className="absolute inset-0 bg-gradient-to-l from-[#311f1d]/70 via-[#2f211c]/20 to-transparent"/><div className="relative mx-auto w-full max-w-[1440px] px-8 py-24 text-white lg:px-20"><p className="mb-4 text-xs tracking-[.22em]">GLITTER ACCESSORIES</p><h1 className="max-w-xl text-4xl font-light leading-tight md:text-6xl">{hero.title}</h1><p className="mt-5 max-w-lg text-sm leading-7">{hero.description}</p><Link href={heroHref} className="mt-8 inline-block bg-white px-8 py-4 text-xs text-[#211e1c]">اكتشفي المجموعة</Link></div></section> : <section className="flex min-h-[430px] items-center justify-center bg-[#f5efed] px-6 text-center"><div><p className="mb-3 text-xs tracking-[.24em] text-[#b98b8f]">GLITTER ACCESSORIES</p><h1 className="text-4xl font-light md:text-6xl">تفاصيل تليق بكِ</h1><p className="mt-5 text-sm text-black/55">اكتشفي قطعك المفضلة من تشكيلتنا.</p><Link href="/shop" className="mt-7 inline-block bg-[#211e1c] px-8 py-4 text-xs text-white">تسوقي الآن</Link></div></section>}
    <div className="mx-auto max-w-[1440px] px-5 py-16 lg:px-10">
      {categories.length > 0 && <section><SectionTitle eyebrow="تسوقي حسب الفئة" title="اختاري ما تحبين"/><div className="grid grid-cols-2 gap-4 md:grid-cols-5">{categories.map((category) => <Link key={category.id} href={`/shop?category=${category.id}`} className="group relative aspect-[.86] overflow-hidden bg-[#f7f3f1]">{category.image_url && <img src={category.image_url} alt={category.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/>}<span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/55 to-transparent p-5 pt-14 text-center text-sm text-white">{category.name}</span></Link>)}</div></section>}
      {offers.length > 0 && <section className="mt-20"><SectionTitle eyebrow="لفترة محدودة" title="عروض مختارة"/><div className="grid gap-4 md:grid-cols-3">{offers.map((offer) => <Link key={offer.id} href={`/shop?offer=${offer.id}`} className="border border-[#ead8d7] bg-[#fbf5f4] p-7"><p className="text-xs text-[#a66f74]">عرض خاص</p><h3 className="mt-3 text-xl">{offer.name}</h3><p className="mt-2 text-xs text-black/55">{offer.description}</p></Link>)}</div></section>}
      <section className="mt-20"><SectionTitle eyebrow="اختيرت لكِ" title="قطع مميزة"/><ProductGrid products={products.filter((product) => product.is_featured).slice(0, 4)}/><div className="mt-10 text-center"><Link href="/shop" className="border border-black/20 px-8 py-3 text-xs">تسوقي جميع القطع</Link></div></section>
    </div><footer className="bg-[#201d1c] px-6 py-12 text-center text-xs text-white/70"><p className="font-serif text-2xl text-white">Glitter</p><p className="mt-3">إكسسوارات مختارة بعناية، لتكمّل أناقتك كل يوم.</p><p className="mt-8">© Glitter Accessories</p></footer>
  </main>;
}

function SectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="mb-9 text-center md:mb-12"><p className="mb-3 text-[11px] tracking-[.24em] text-[#b98b8f]">{eyebrow}</p><h2 className="text-[28px] font-light md:text-[37px]">{title}</h2><span className="mx-auto mt-4 block h-px w-10 bg-[#cfabad]"/></div>; }
function ProductGrid({ products }: { products: Awaited<ReturnType<typeof getProducts>> }) { return products.length ? <div className="grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-4 md:gap-6">{products.map((product) => <article key={product.id}><Link href={`/product/${product.id}`} className="block aspect-[.79] overflow-hidden bg-[#f7f3f1]">{product.image_url && <img src={product.image_url} alt={product.name} className="h-full w-full object-cover transition duration-700 hover:scale-[1.035]"/>}</Link><h3 className="pt-4 text-center text-sm"><Link href={`/product/${product.id}`}>{product.name}</Link></h3><div className="mt-2 flex justify-center gap-2 text-sm"><strong><Price amount={product.price}/></strong>{product.old_price && <span className="text-xs text-[#aaa19d] line-through"><Price amount={product.old_price}/></span>}</div></article>)}</div> : <p className="py-10 text-center text-sm text-black/50">لا توجد منتجات معروضة حاليًا.</p>; }
