"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { placeOrder } from "@/actions/orders";

type Zone={id:string;name:string;fee:number};
export default function CheckoutForm({zones}:{zones:Zone[]}){
  const [zoneId,setZoneId]=useState(zones[0]?.id||"");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [order,setOrder]=useState<{order_number:number;total:number}|null>(null);
  const zone=useMemo(()=>zones.find((z)=>z.id===zoneId),[zones,zoneId]);
  async function submit(formData:FormData){setBusy(true);setError("");let cart:Record<string,number>={};try{cart=JSON.parse(localStorage.getItem("glitter-cart-v1")||"{}")}catch{}
    const items=Object.entries(cart).map(([productId,quantity])=>({productId,quantity}));if(!items.length){setError("سلة التسوق فارغة.");setBusy(false);return;}
    const result=await placeOrder({name:formData.get("name"),phone:formData.get("phone"),email:formData.get("email")||"",address:formData.get("address"),zoneId,coupon:formData.get("coupon"),items});
    if(!result.ok){setError(result.error);setBusy(false);return;}localStorage.removeItem("glitter-cart-v1");setOrder({order_number:result.order.order_number,total:result.order.total});setBusy(false);
  }
  if(order)return <main dir="rtl" className="min-h-screen bg-[#fffdfc] px-5 py-20 text-center"><h1 className="text-3xl font-light">شكرًا لطلبك</h1><p className="mt-5 text-sm">رقم الطلب #{order.order_number} · الإجمالي {Number(order.total).toFixed(2)} ₪</p><Link href="/shop" className="mt-8 inline-block bg-[#211e1c] px-8 py-3 text-xs text-white">متابعة التسوق</Link></main>;
  return <main dir="rtl" className="min-h-screen bg-[#fffdfc] px-5 py-10 text-[#201d1c]"><div className="mx-auto max-w-5xl"><Link href="/" className="font-serif text-2xl">Glitter</Link><h1 className="my-9 text-3xl font-light">إتمام الطلب</h1><div className="mb-6 border border-[#d6b6b7] bg-[#fbf5f4] p-4 text-xs">يمكنك إتمام الطلب كزائرة دون إنشاء حساب.</div><form action={submit} className="grid gap-10 lg:grid-cols-[1fr_360px]"><div className="space-y-8"><section><h2 className="mb-5 text-lg">معلومات التواصل</h2><div className="grid gap-4 md:grid-cols-2">{[["الاسم الكامل","name","text"],["رقم الجوال","phone","tel"],["البريد الإلكتروني (اختياري)","email","email"]].map(([label,name,type])=><label key={name} className="text-xs">{label}<input name={name} type={type} required={name!=="email"} className="mt-2 w-full border border-black/15 bg-white p-3"/></label>)}</div></section><section><h2 className="mb-5 text-lg">عنوان التوصيل</h2><div className="grid gap-4 md:grid-cols-2"><label className="text-xs">منطقة التوصيل<select name="zone" value={zoneId} onChange={(e)=>setZoneId(e.target.value)} required className="mt-2 w-full border border-[#b98b8f] bg-white p-3">{zones.map((z)=><option key={z.id} value={z.id}>{z.name} — {z.fee} ₪</option>)}</select></label><label className="text-xs">العنوان بالتفصيل<textarea name="address" required minLength={5} maxLength={500} className="mt-2 min-h-24 w-full border border-black/15 bg-white p-3"/></label></div></section><label className="block text-xs">كود الخصم (اختياري)<input name="coupon" className="mt-2 w-full max-w-sm border border-black/15 p-3"/></label></div><aside className="h-fit bg-[#f5efed] p-6"><h2 className="text-lg">ملخص التوصيل</h2><div className="mt-5 flex justify-between border-b border-black/10 pb-4 text-sm"><span>رسوم التوصيل{zone?` · ${zone.name}`:""}</span><strong>{zone?.fee??0} ₪</strong></div><p className="mt-4 text-xs leading-6 text-black/55">سيتم التحقق من أسعار المنتجات والكوبون والمخزون على الخادم قبل تثبيت الطلب.</p>{error&&<p role="alert" className="mt-4 text-xs text-red-700">{error}</p>}<button disabled={busy||!zones.length} className="mt-6 w-full bg-[#211e1c] py-4 text-xs text-white disabled:opacity-50">{busy?"جارٍ إرسال الطلب...":"تأكيد الطلب · الدفع عند الاستلام"}</button></aside></form></div></main>;
}
