import Link from "next/link";
import { notFound } from "next/navigation";
import { getProduct, getProducts } from "@/lib/store";
import AddToCartButton from "@/components/AddToCartButton";
import FavoriteButton from "@/components/FavoriteButton";

export default async function ProductPage({params}:{params:Promise<{id:string}>}) {
  const {id}=await params; const product=await getProduct(id); if(!product) notFound();
  const similar=(await getProducts({category:product.category_id||undefined})).filter((p)=>p.id!==id).slice(0,4);
  const gallery=product.image_urls?.length?product.image_urls:product.image_url?[product.image_url]:[];
  return <main dir="rtl" className="min-h-screen bg-[#fffdfc] text-[#201d1c]"><header className="border-b border-black/10 px-6 py-6"><Link href="/" className="font-serif text-2xl">Glitter</Link><Link href="/cart" className="float-left text-xs">السلة</Link></header><div className="mx-auto max-w-6xl px-5 py-12"><nav className="mb-8 text-xs text-black/45"><Link href="/shop">المتجر</Link> / {product.name}</nav><div className="grid gap-10 md:grid-cols-2"><div className="grid grid-cols-2 gap-2">{gallery.map((image,index)=><div key={image} className={`aspect-[.82] bg-[#f7f3f1] ${index===0&&gallery.length%2===1?"col-span-2":""}`}><img src={image} alt={`${product.name} ${index+1}`} className="h-full w-full object-cover"/></div>)}</div><section className="py-5"><p className="text-xs tracking-[.2em] text-[#b98b8f]">GLITTER ACCESSORIES</p><h1 className="mt-4 text-3xl font-light">{product.name}</h1><p className="mt-4 text-xl">{product.price} ₪ {product.old_price&&<del className="mr-2 text-sm text-black/40">{product.old_price} ₪</del>}</p><p className="mt-6 text-sm leading-8 text-black/60">{product.description}</p><p className="mt-5 text-xs">{product.stock>0?`متوفر في المخزون (${product.stock})`:"نفد من المخزون"}</p><div className="mt-8 flex flex-wrap gap-3"><AddToCartButton productId={product.id} disabled={product.stock<1}/><FavoriteButton productId={product.id}/></div><Link href="/checkout" className="mt-4 block w-fit border border-black/20 px-6 py-3 text-xs">شراء الآن</Link></section></div>{similar.length>0&&<section className="mt-20"><h2 className="mb-7 text-2xl font-light">قد يعجبك أيضًا</h2><div className="grid grid-cols-2 gap-5 md:grid-cols-4">{similar.map((item)=><Link key={item.id} href={`/product/${item.id}`}><div className="aspect-[.8] bg-[#f7f3f1]">{item.image_url&&<img src={item.image_url} alt={item.name} className="h-full w-full object-cover"/>}</div><p className="mt-3 text-center text-sm">{item.name}</p><p className="mt-2 text-center text-sm">{item.price} ₪</p></Link>)}</div></section>}</div></main>;
}
